name: Sending mail

on:
    push:
        branches:
            - main

jobs:
    mailsendingjob:
        runs-on: ubuntu-latest

        steps:
            - name: print something
              run: echo "Testing workflow"

            - name: Send Email
              uses: hilarion5/send-mail@v1
              with:
                smtp-server: smtp.example.com
                smtp-port: 465
                smtp-secure: true
                from-email: ${{secrets.ACCOUNT}}
                to-email: writemeajithak@gmail.com
                username: ${{secrets.ACCOUNT}}
                password: ${{secrets.MAIL_PASSWORD}}
                subject: Test Email
                body: This is a test email sent from GitHub Actions.
