name: Sending mail

on:
    push:
        branches:
            - main

jobs:
    mailsendingjob:
        runs-on: ubuntu-latest

        steps:
            - name: print something
              run: echo "Testing workflow"

            - name: send a mail
              if: ${{ always() }}
              uses: devellany/send-mailer@v1.0.2
              with:
                host: smtp.google.com
                # Optional port (defaults to 465)
                port: 465
                account: ${{secrets.ACCOUNT}}
                password: ${{secrets.MAIL_PASSWORD}}
                sender: Ajith kumar G
                from: ${{secrets.MAIL_ADDRESS}}
                to: writemajithak@gmail.comm
                subject: Github CI/CD Pipeline.
                body: You got mail by github workflow.